### ISSUE TITLE
problem with %include 

### ISSUE THREAD

**Issue by power9799** [tensorflow/swift#373] opened 2020-01-31 15:03 UTC
(%include "EnableIPythonDisplay.swift"  )is giving an error % is not an unary operator. When I changed it to # still gives me an error.
 ( let trainDataset: Dataset<IrisBatch> = Dataset(
    contentsOfCSVFile: trainDataFilename, hasHeader: true,
    featureColumns: [0, 1, 2, 3], labelColumns: [4]
).batched(batchSize) )  is giving an error saying iris batch doesn't conform with the tensor group. I think it is because %(include "TutorialDatasetCSVAPI.swift") is not working.

We are using [JIRA](https://bugs.swift.org) instead of GitHub issues to track
our work in order to integrate more effectively with the rest of the Swift
ecosystem.

Before opening a new issue, please [search the existing
issues](https://bugs.swift.org/issues/?jql=project%20%3D%20TF) to see if your
issue has already been asked. If it's open, you can _Add Vote_ to request
the issue be prioritized. And you can start watching the issue to receive
updates.

If there are no related issues in JIRA, please file a new ticket by using one
of the links below corresponding to the nature of your issue:

  - [Create a bug](https://bugs.swift.org/secure/CreateIssue.jspa?issuetype=10006&pid=10100)
  - [Create a new feature request (Story)](https://bugs.swift.org/secure/CreateIssue.jspa?issuetype=10001&pid=10100)
  - [Create a new clean up / internal improvement](https://bugs.swift.org/secure/CreateIssue.jspa?issuetype=10003&pid=10100)

**Comment by ematejska** [comment] 2020-01-31 18:11
Where/how are you running this?  Please describe your development environment.

**Comment by power9799** [comment] 2020-02-01 14:54
I'm running on Xcode 11.3 beta with 12.23.19 TensorFlow snapshot.

**Comment by rickwierenga** [comment] 2020-02-04 18:28
I'm pretty sure `%` is a Jupyter thing and therefore can't be used with Xcode. Check out https://colab.research.google.com or [google/swift-jupyter](https://github.com/google/swift-jupyter) :)

**Comment by BradLarson** [comment] 2020-02-05 18:32
Unfortunately, it is unclear as to the cause of this issue, and we can't reproduce this on our end. If you have more information to add to this, we can revisit this, but in the mean time I'll be closing this out.

**Closed by BradLarson** 2020-02-05 18:32 UTC

**Comment by power9799** [comment] 2020-02-07 17:27
I'm running it on Xcode 11.3 beta with 12.23.19 TensorFlow snapshot.
import Foundation
import TensorFlow
import Python
%include "EnableIPythonDisplay.swift"
IPythonDisplay.shell.enable_matplotlib("inline")

the errors are  %' is not a prefix unary operator 
and Use of unresolved identifier 'IPythonDisplay'

**Comment by rickwierenga** [comment] 2020-02-07 21:18
I'm pretty sure `%` is a Jupyter thing and therefore can't be used with Xcode. Check out https://colab.research.google.com or google/swift-jupyter :)
