### ISSUE TITLE
Can't use po in LLDB debugger 

### ISSUE THREAD

**Issue by acarrera94** [tensorflow/swift#409] opened 2020-03-13 20:56 UTC
This is probably related to https://github.com/tensorflow/swift/issues/382

While using the latest Xcode toolchain and stopping at a breakpoint, I try to `po` for example: 
`(lldb) po input.sequence `
and I get the following: 

> Cannot create Swift scratch context (couldn't load the Swift stdlib)Cannot create Swift scratch context (couldn't load the Swift stdlib)Shared Swift state for Transformer-Translation could not be initialized.
> The REPL and expressions are unavailable.

I was trying to use this since in the related issue we can't see variable values

**Comment by dan-zheng** [comment] 2020-03-21 15:41
Let's close this issue as a duplicate of #382, which tracks Xcode debugging issues with Swift for TensorFlow toolchains.

The underlying issue (SR-12127) is Xcode-specific: Xcode debugger uses system `lldb` rather than toolchain `lldb`. Unfortunately, our team can't fix it. The issue also applies to toolchains from [swift.org/download](https://swift.org/download).

**Closed by dan-zheng** 2020-03-21 15:41 UTC
