### ISSUE TITLE
XCode 9.4 - Swift 4.2-dev cannot import either REPL or inside XCode IDE

### ISSUE THREAD

**Issue by nxphi47** [tensorflow/swift#41] opened 2018-06-11 14:34 UTC
Hi there,

I installed swift for tensorflow from https://github.com/tensorflow/swift/blob/master/Installation.md and install the pkg file `swift-tensorflow-DEVELOPMENT-2018-06-01-a-osx.pkg`

and add `export PATH=/Library/Developer/Toolchains/swift-latest/usr/bin:"${PATH}"
 ` to the $PATH 

as well as selecting swift-for-tensorflow toolchains in Components/Toolchains

I cannot import in command line or import Tensorflow inside the IDE.

Some infor:
Xcode: Version 9.4 (9F1027a)
Swift: `Swift version 4.2-dev (LLVM 04bdb56f3d, Clang b44dbbdf44, Swift 70260a59ef)`

Thanks,

**Comment by johndpope** [comment] 2018-06-11 19:16
it's working for me in ide - need to update the readme - check these notes
https://github.com/tensorflow/swift/issues/10#issuecomment-385167803

https://github.com/tensorflow/swift-models/issues/10

**Comment by dan-zheng** [comment] 2018-06-22 17:21
Hi @nxphi47,
Sorry for the late follow-up - are you still having problems using the 06-01 toolchain?
I'm able to use the 06-01 toolchain and `import TensorFlow` in a Playground with Xcode 9.4.1 (9F2000).

**Comment by dan-zheng** [comment] 2018-06-30 11:18
Closing, since bug is not reproducible.
Please update to the [latest prebuilt packages](https://github.com/tensorflow/swift/blob/master/Installation.md#pre-built-packages).

**Closed by dan-zheng** 2018-06-30 11:18 UTC
