### ISSUE TITLE
Clang error with Release 0.12

### ISSUE THREAD

**Issue by SercanKaraoglu** [tensorflow/swift#574] opened 2020-11-20 08:47 UTC
After upgrading to Tensorflow 0.12 I started to get compilation error from one of my project dependencies https://github.com/apple/swift-nio-ssl/issues/254#event-4019465227 . I have described the issue there and created a pr, however I was requested to create the issue in here the upstream project because it seems like a clang error. 

```
139:7: error: missing '#include <stdlib.h>'; 'abort' must be declared before it is used
      abort();
      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include/stdlib.h:131:7: note: declaration here is not visible
void     abort(void) __cold __dead2;
```

**Comment by texasmichelle** [comment] 2020-12-02 18:40
Are you able to reproduce this error using a stock Swift toolchain?

**Comment by SercanKaraoglu** [comment] 2020-12-02 18:45
I just saw relevant issue here https://github.com/apple/swift-nio-ssl/issues/259 seems like another user reproduced the same error there with stock swift toolchain but not the library author himself. Seems like a clang issue

**Comment by pschuh** [comment] 2020-12-09 18:04
Since it is an upstream issue, I'll close this.

**Closed by pschuh** 2020-12-09 18:04 UTC

**Comment by Austinpayne** [comment] 2020-12-15 00:24
I'm not entirely sure this is an upstream issue: https://github.com/apple/swift-nio-ssl/issues/259#issuecomment-744873117
