### ISSUE TITLE
Is the Swift API identical to the python and Java implementations of Tensorflow yet?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/swift#107] opened 2019-02-07 13:37 UTC
Do you know when this will be available?

**Comment by rxwei** [comment] 2019-02-12 11:35
They are not identical. The backend is.

**Comment by rxwei** [comment] 2019-02-12 11:37
I'm going to close this issue because it's not a bug. You are welcome to ask questions on the swift@tensorflow.org mailing list. Thanks!

**Closed by rxwei** 2019-02-12 11:37 UTC
