### ISSUE TITLE
error: Couldn't lookup symbols:

### ISSUE THREAD

**Issue by MuthumbiAlex** [tensorflow/swift#173] opened 2019-04-22 12:41 UTC
Can anyone help me with removing this error below? 
"error: Couldn't lookup symbols:
  type metadata accessor for TensorFlow.Tensor
  protocol witness table for TensorFlow.Tensor<A> : TensorFlow.TensorArrayProtocol in TensorFlow
  type metadata accessor for TensorFlow.TensorElementLiteral
  protocol witness table for TensorFlow.TensorElementLiteral<A> : TensorFlow.TensorArrayProtocol in TensorFlow
  protocol conformance descriptor for <A where A: TensorFlow.TensorArrayProtocol> Swift.Array<A> : TensorFlow.TensorArrayProtocol in TensorFlow
  protocol witness table for Swift.Float : TensorFlow.TensorFlowScalar in TensorFlow
  _TFE_DeleteOp
  _TFE_NewOp
  _TFE_OpSetAttrBool
  _TFE_OpSetAttrInt
  _TFE_OpSetAttrType
  _TF_DeleteStatus
  _TF_NewStatus
  ___tf_tensor_from_scalar
  __swift_FORCE_LOAD_$_swiftPython
  __swift_tfc_CheckOk
  __swift_tfc_CreateTensorHandleFromC
  __swift_tfc_EagerExecute
  __swift_tfc_GetGlobalEagerContext
  __swift_tfc_OpAddInputFromTensorGroup
  __swift_tfc_OpSetDeviceFromScope
"

The code am running used to run before, but i upgraded to Tensorflow 2.0, and then installed "swift for tensorflow release 0.2 2019-03-02." 
<img width="1399" alt="Screen Shot 2019-04-22 at 3 40 58 PM" src="https://user-images.githubusercontent.com/26058451/56500842-11458c80-6515-11e9-85bd-adec83212a96.png">
<img width="1399" alt="Screen Shot 2019-04-22 at 3 40 49 PM" src="https://user-images.githubusercontent.com/26058451/56500843-11de2300-6515-11e9-89bf-07f8b575ee44.png">

**Comment by rxwei** [comment] 2019-04-22 23:16
Thanks for reporting this bug!  We will look into this.  It is likely because we are missing linker flag `-ltensorflow` in our toolchain when the toolchain talks to Xcode Playgrounds. @dan-zheng can provide more context.

Our recommended prototyping environment is [Colaboratory](https://colab.research.google.com/github/tensorflow/swift/blob/master/notebooks/blank_swift.ipynb), but supporting Xcode is definitely on our list since Xcode sometimes has a better user experience on macOS.

**Comment by dan-zheng** [comment] 2019-04-22 23:25
I'm able to reproduce the linker errors in a playground using Xcode 10.2 beta 4.
I don't get any errors using Xcode 10.0.

I'll attempt a linker error fix now - not confident it will work.

**Comment by MuthumbiAlex** [comment] 2019-04-23 08:43
Thanks alot Richard and Dan, I will be on the lookout for a fix.

**Comment by dan-zheng** [comment] 2019-04-24 07:49
I made [a failed attempt](https://github.com/dan-zheng/swift/tree/tensorflow-xcode10-2-playground-fix-attempt) to fix the Xcode 10.2 Playgrounds "Couldn't lookup symbols" error.

I tried to add some default linker flags (`-ltensorflow`, `-lswiftTensorFlow`, and `-lswiftPython`) for Darwin toolchains. Previously, [this strategy](https://github.com/apple/swift/blob/0ce7594bb0e94517742f8b15ea1734d1ddc22b4f/lib/Driver/UnixToolChains.cpp#L290) was used to fix [similar "Couldn't lookup symbols:" errors](https://github.com/google/swift/issues/4) for Linux toolchains.

I do feel the approach is in the right direction, perhaps the linker flags aren't being specified at the right place for Playgrounds.

**Comment by iamlogiq** [comment] 2019-04-30 16:59
Any update on a fix? Experiencing the same problem when using playgrounds with Xcode Version 10.2.1 (10E1001)

**Comment by dan-zheng** [comment] 2019-04-30 18:13
No fix yet unfortunately. I haven't continued looking into the issue.

We're working on downstreaming changes from `master` branch into `tensorflow` branch: that has some chance to fix/change the nature of the issue.

**Comment by mertensu** [comment] 2019-05-15 09:01
Hi,

I get the following lookup symbols error (even) in XCode 10.0 using the current SFT version 0.3.1:

```
Playground execution failed:

error: Couldn't lookup symbols:
  __swift_FORCE_LOAD_$_swiftPython
```

**Comment by mertensu** [comment] 2019-05-17 07:11
Hi,

for anyone getting the same (or a similar) error message. Using the swift package manager to generate the project seems to work:

```
mkdir my_project
cd my_project
swift package init --type executable
swift package generate-xcodeproj
swift build
```

This sets up a project using the swift package manager. In my case, I could then open the project in XCode and import TensorFlow without the _Couldn't lookup symbols_ error.

**Comment by hfoffani** [comment] 2019-05-18 20:27
In my environment I couldn't make it work by using the swift package manager.

It does work using the workaround in https://github.com/tensorflow/swift/issues/177#issuecomment-493102177 However, as far as I know, it's not possible to use this workaround in Playgrounds which the OP of this issue refers to.

**Comment by marcrasi** [comment] 2019-11-20 18:44
Closing because this is old and may no longer be broken. Feel free to reopen or file a new issue :)

**Closed by marcrasi** 2019-11-20 18:44 UTC
