### ISSUE TITLE
S4TF for macOS fails to build with LLDB Python3 support 

### ISSUE THREAD

**Issue by dbonner** [tensorflow/swift#359] opened 2020-01-10 06:12 UTC
I am using macOS Catalina 10.15.3 beta and Xcode 11.3.
I am trying to build S4TF for macOS with LLDB Python3 support so that I can use swift-jupyter.

Steps:

brew install python
brew install python@2
(Close and reopen terminal)
pip2 install numpy future six
sudo chown -R $(whoami) /usr/local/lib/pkgconfig
chmod u+w /usr/local/lib/pkgconfig
brew install cmake ninja
brew cask install java
(Download bazel-0.27.1-installer-darwin-x86_64.sh)
chmod +x bazel-0.27.1-installer-darwin-x86_64.sh
./bazel-0.27.1-installer-darwin-x86_64.sh
mkdir swift-source
cd swift-source
git clone https://github.com/apple/swift.git -b tensorflow
./swift/utils/update-checkout --clone --scheme tensorflow
cd swift
utils/build-toolchain-tensorflow

The script almost finishes but then ends on the following error code while trying to build swiftpm-macosx-x86_64:

/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:742:2: error: derivative not in the same file as the original function
@derivative(of: tan, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:747:2: error: derivative not in the same file as the original function
@derivative(of: asin, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:751:2: error: derivative not in the same file as the original function
@derivative(of: acos, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:755:2: error: derivative not in the same file as the original function
@derivative(of: atan, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:759:2: error: derivative not in the same file as the original function
@derivative(of: sinh, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:763:2: error: derivative not in the same file as the original function
@derivative(of: cosh, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:767:2: error: derivative not in the same file as the original function
@derivative(of: tanh, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:772:2: error: derivative not in the same file as the original function
@derivative(of: asinh, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:776:2: error: derivative not in the same file as the original function
@derivative(of: acosh, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:780:2: error: derivative not in the same file as the original function
@derivative(of: atanh, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:784:2: error: derivative not in the same file as the original function
@derivative(of: expm1, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:788:2: error: derivative not in the same file as the original function
@derivative(of: log1p, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:792:2: error: derivative not in the same file as the original function
@derivative(of: erf, wrt: x)
 ^
/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/lib/swift/macosx/Darwin.swiftmodule/x86_64.swiftinterface:796:2: error: derivative not in the same file as the original function
@derivative(of: erfc, wrt: x)
 ^
<unknown>:0: error: failed to load module 'Darwin'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/swift/Darwin.swiftmodule/x86_64.swiftinterface:720:15: error: use of unresolved identifier 'lgammaf_r'
  let value = lgammaf_r(CFloat(x), &sign)
              ^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/swift/Darwin.swiftmodule/x86_64.swiftinterface:725:15: error: use of unresolved identifier 'lgamma_r'
  let value = lgamma_r(CDouble(x), &sign)
              ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/swift/Darwin.swiftmodule/x86_64.swiftinterface:730:15: error: use of unresolved identifier 'lgammal_r'
  let value = lgammal_r(CLongDouble(x), &sign)
              ^~~~~~~~~
--- bootstrap: error: Command '['env', 'SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk', 'SWIFTCI_USE_LOCAL_DEPS=1', 'DYLD_LIBRARY_PATH=/Users/daniel/swift-source/build/buildbot_osx/swiftpm-macosx-x86_64/x86_64-apple-macosx/bootstrap/lib:/Users/daniel/swift-source/build/buildbot_osx/llbuild-macosx-x86_64/lib', 'SWIFT_EXEC=/Users/daniel/swift-source/swift/swift-nightly-install/Library/Developer/Toolchains/swift-tensorflow-LOCAL-2020-01-10-a.xctoolchain/usr/bin/swiftc', 'SWIFTPM_PD_LIBS=/Users/daniel/swift-source/build/buildbot_osx/swiftpm-macosx-x86_64/x86_64-apple-macosx/bootstrap/pm', '/Users/daniel/swift-source/build/buildbot_osx/swiftpm-macosx-x86_64/x86_64-apple-macosx/bootstrap/bin/swift-build', '--disable-sandbox', '--disable-index-store', '--build-path', '/Users/daniel/swift-source/build/buildbot_osx/swiftpm-macosx-x86_64', '--configuration', 'release']' returned non-zero exit status 1
./utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
./utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
daniel@Daniels-iMac swift %

**Comment by dan-zheng** [comment] 2020-01-10 06:54
Oops, sorry about that! It's bad that we didn't catch this macOS toolchain regression. The regression was introduced in https://github.com/apple/swift/pull/28933: it wasn't caught because `apple/swift` CI doesn't test macOS toolchain builds.

This issue is a duplicate of TF-1101, which I believe @marcrasi is investigating.

**Comment by marcrasi** [comment] 2020-01-11 04:26
I have just merged https://github.com/apple/swift/pull/29137, which should fix this. I have not confirmed yet, because toolchain builds on my mac are being a bit flaky for seemingly-unrelated reasons. I'll close this issue when I or someone else confirms that it's fixed.

**Comment by dbonner** [comment] 2020-01-11 09:02
Hi marcrasi,
I get the following error now while the build script is trying to build swiftPM:/Users/daniel/swift-source/swiftpm: error: manifest parse error(s):
swift (LLVM option parsing): for the   --enable-experimental-cross-file-derivative-registration option: may only occur zero or one times!
Cheers,
Dan

**Comment by marcrasi** [comment] 2020-01-11 21:01
Yep, I can reproduce that now. I'll try out a few things and hopefully discover a fix soon.

**Comment by marcrasi** [comment] 2020-01-22 18:44
Now actually fixed, in https://github.com/apple/swift/pull/29156

**Closed by marcrasi** 2020-01-22 18:44 UTC
